 name: Reality
 version: 1.0
 description: Custom RPG for MineFutureMC
 author: Cheesepro
 website: http://RealityMC.com
 main: me.cheesepro.reality.Reality
 depend: [Vault, WorldGuard, WorldEdit, PermissionsEX]

 commands:
   reality:
     description: Reality's main command
     permission: reality.default
     permission-message: You don't have Permission!!
 permissions:
   reality.admin:
     default: op
   reality.default:
     defualt: true