 name: Reality
 version: 1.1
 description: Custom RPG for MineFutureMC
 author: Cheesepro
 website: http://RealityMC.com
 main: me.cheesepro.reality.Reality
 depend: [Vault, WorldGuard, WorldEdit, PermissionsEx, Citizens, MVdWPlaceholderAPI]

 commands:
   reality:
     description: Reality's main command
     permission: reality.default
     permission-message: You don't have Permission!!
   bossroom:
     description: Bossroom command
     permission: reality.default
     permission-message: You don't have Permission!!
   room:
     description: Bossroom command (short)
     permission: reality.default
     permission-message: You don't have Permission!!
   assignrandomrank:
     description: Assign random rank
 permissions:
   reality.admin:
     default: op
   reality.default:
     default: true